# Generated by Django 3.2 on 2021-08-05 08:09

import about.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=14, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=14, null=True)),
                ('address', models.CharField(blank=True, max_length=14, null=True)),
                ('name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number_np', models.CharField(blank=True, max_length=14, null=True)),
                ('contact_email_np', models.CharField(blank=True, max_length=255, null=True)),
                ('province_np', models.CharField(blank=True, max_length=14, null=True)),
                ('address_np', models.CharField(blank=True, max_length=14, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=about.models.upload_about_organization_picture)),
                ('category', models.CharField(blank=True, choices=[('Leading', 'Leading'), ('Support', 'Support'), ('Co-Support', 'Co-Support')], default='C', max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=14, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_website', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_social_media', models.CharField(blank=True, max_length=1024, null=True)),
                ('title_np', models.CharField(max_length=255)),
                ('description_np', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number_np', models.CharField(blank=True, max_length=14, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(blank=True, choices=[('L', 'Leads'), ('M', 'Members')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('lead_type', models.CharField(blank=True, choices=[('P', 'Provincial Lead'), ('T', 'Team Lead')], default='P', max_length=1, null=True)),
                ('province', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=about.models.upload_about_picture)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('primary_contact', models.CharField(max_length=14)),
                ('secondary_contact', models.CharField(blank=True, max_length=14, null=True)),
                ('qualifications', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1000)),
                ('resume', models.FileField(blank=True, null=True, upload_to=about.models.upload_about_resume)),
                ('is_approved', models.BooleanField(default=False)),
                ('province_np', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('position_np', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact_np', models.CharField(blank=True, max_length=14, null=True)),
                ('secondary_contact_np', models.CharField(blank=True, max_length=14, null=True)),
                ('qualifications_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('description_np', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('AN', 'announcement'), ('NE', 'news'), ('VI', 'videos'), ('AR', 'articals')], max_length=2, null=True)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('video_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', max_length=1024, null=True, upload_to=about.models.upload_resources_image)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('title_np', models.CharField(blank=True, max_length=255, null=True)),
                ('content_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('summary_np', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=255)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suppliers', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment_type_np', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_np', models.IntegerField(blank=True, null=True)),
                ('model_number_np', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('suppliers_np', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks_np', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.hospital')),
            ],
        ),
    ]
