# Generated by Django 3.2 on 2021-12-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.CharField(choices=[('MBA', 'MBA'), ('BICT', 'BICT')], max_length=255)),
                ('semester', models.CharField(choices=[('2-semester', '2-semester'), ('5-semester', '5-semester'), ('7-semester', '7-semester'), ('master', 'master')], max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freshers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contx_no', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('Female', 'Female')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.freshers')),
            ],
        ),
    ]
