# Generated by Django 3.2 on 2021-06-20 02:49

import about.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, default='default.jpg', max_length=1024, null=True, upload_to=about.models.upload_about_picture)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('primary_contact', models.CharField(max_length=14)),
                ('secondary_contact', models.CharField(blank=True, max_length=14, null=True)),
                ('qualifications', models.CharField(max_length=1024)),
                ('resume', models.FileField(blank=True, null=True, upload_to=about.models.upload_about_resume)),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
