# Generated by Django 3.2 on 2021-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
