# Generated by Django 3.2 on 2021-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210805_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_type',
            field=models.CharField(blank=True, choices=[('L', 'Leads'), ('M', 'Members'), ('T', 'Management')], max_length=1, null=True),
        ),
    ]
