# Generated by Django 3.2 on 2021-09-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_team_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_type',
            field=models.CharField(blank=True, choices=[('L', 'Leads'), ('M', 'Members')], max_length=1, null=True),
        ),
    ]
