# Generated by Django 3.2 on 2021-06-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_members_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='account_from',
        ),
    ]
