# Generated by Django 3.2 on 2021-06-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_member_account_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('L', 'Leads'), ('M', 'Members')], max_length=1),
        ),
    ]
