# Generated by Django 3.2 on 2021-09-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_team_member_type'),
        ('about', '0005_auto_20210906_0822'),
    ]

    operations = [
    ]
