# Generated by Django 3.2 on 2021-09-12 12:29

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_merge_20210912_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.CharField(max_length=1024)),
                ('request_for', models.CharField(max_length=1024)),
                ('support_provided', models.CharField(max_length=1024)),
                ('details', models.CharField(max_length=1024)),
                ('request_from_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('request_for_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('support_provided_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('details_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=about.models.upload_solve_files)),
                ('document', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='member_type',
            field=models.CharField(blank=True, choices=[('L', 'Leads'), ('M', 'Members'), ('T', 'Management')], max_length=1, null=True),
        ),
    ]
