# Generated by Django 3.2 on 2021-06-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_member_member_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Team',
        ),
    ]
