# Generated by Django 3.2 on 2021-06-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_team_member_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=14, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_website', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_social_media', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
