# Generated by Django 3.2 on 2021-07-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_auto_20210626_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=14, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=14, null=True)),
                ('address', models.CharField(blank=True, max_length=14, null=True)),
                ('name_np', models.CharField(max_length=255)),
                ('contact_number_np', models.CharField(blank=True, max_length=14, null=True)),
                ('contact_email_np', models.CharField(blank=True, max_length=255, null=True)),
                ('province_np', models.CharField(blank=True, max_length=14, null=True)),
                ('address_np', models.CharField(blank=True, max_length=14, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=255)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suppliers', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment_type_np', models.CharField(max_length=255)),
                ('unit_np', models.IntegerField(blank=True, null=True)),
                ('model_number_np', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('suppliers_np', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks_np', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.hospital')),
            ],
        ),
    ]
