# Generated by Django 3.2 on 2021-07-29 08:14

import about.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0015_equipment_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type_np',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name_np',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('AN', 'announcement'), ('NE', 'news'), ('VI', 'videos'), ('AR', 'articals')], max_length=2, null=True)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('video_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', max_length=1024, null=True, upload_to=about.models.upload_resources_image)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('title_np', models.CharField(blank=True, max_length=255, null=True)),
                ('content_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug_np', models.CharField(blank=True, max_length=1024, null=True)),
                ('summary_np', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
